# Generated by Django 2.2.5 on 2019-09-24 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=100)),
                ('adult_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('kid_price', models.DecimalField(decimal_places=2, default=2.0, max_digits=8)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_creator', to='user.User')),
            ],
        ),
    ]
