# Generated by Django 2.2.5 on 2019-09-25 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('spiritual', 'SPIRITUAL'), ('religious', 'RELIGIOUS'), ('charity', 'CHARITY'), ('social', 'SOCIAL'), ('other', 'OTHER')], default='other', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('adult_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('kid_price', models.DecimalField(decimal_places=2, default=2.0, max_digits=8)),
            ],
        ),
    ]
